import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import { Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Foot from "./components/Foot";







const noto_Serif_Bengali = Noto_Serif_Bengali({
 
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${noto_Serif_Bengali.className

      }h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        
        {children}
        <p>আজকের বাজারের দাম এক নজরে</p>
      
      <Foot></Foot>
        </body>
    </html>
  );
}
